name: civic_bridge_app
description: "Civic Bridge – Public Issue Reporting System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (stable & compatible)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0

  # Media & state
  image_picker: ^1.1.2
  provider: ^6.1.2

  # Maps & location (ADD LATER – Day 4)
  # google_maps_flutter: ^2.6.1
  # geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
